services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
      - "50051:50051"
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  postgres_data:
