# Generated by Django 4.2.30 on 2026-05-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curriculo_lattes',
            field=models.URLField(blank=True, null=True),
        ),
    ]
